updating to python3.7 so we can properly support tkinker in sync with Windows version

updateToPy37.sh is supposed to do it but has Issues.
had to change a few lines from website i copied it from, and then the install messes up
mostly the default install location and some other stuff

installPy37.sh was built to fix that but still has Issues
some seem to stem from pip already having a 3.5 install

so i moved /usr/local/python3.5 aside and then created getPipStuff
which starts off ok but gives whole bunch of issues.  Maybe some of this doesnt work in 3.7?
but modac_server and gtk gui seem to work ok.

moTkKiln doesnt - has issue with tkinter not being up to date - or so it seems with StringVar().trace_add() not working.
or it didnt before I removed py35
oops now server doesnt run either

errors from below...
scipy ... still trying to use python3.5

move /usr/local/lib/python3.5 to hide_py35

use pip3 instead of python3 -m pip....
nope
 sudo apt-get remove python-dev python3-dev
then retry install

ugh this is such a mess.
gonna try a build from scratch - pi Buster starts at 3.7.3 so that would be better

---------------------------
pi@modacServer:~/MODAC_Dev/setupPi $ ./getPip*
#!/bin/sh -v
sudo python3 -m pip install --upgrade pip setuptools wheel
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pip in /usr/local/lib/python3.5/dist-packages (20.2.2)
Requirement already up-to-date: setuptools in /usr/local/lib/python3.5/dist-packages (49.6.0)
Requirement already up-to-date: wheel in /usr/local/lib/python3.5/dist-packages (0.35.1)
#
# need latest numpy, scipy etc
sudo python3 -m pip install -U matplotlib scipy numpy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting matplotlib
  Downloading https://www.piwheels.org/simple/matplotlib/matplotlib-3.0.3-cp35-cp35m-linux_armv7l.whl (10.9 MB)
     |████████████████████████████████| 10.9 MB 20 kB/s 
Collecting scipy
  Using cached scipy-1.4.1.tar.gz (24.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpf029ybs7
         cwd: /tmp/pip-install-hulha8bs/scipy
    Complete output (114 lines):
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_lapack_info:
      libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    system_info:
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/lib/atlas-base
      libraries lapack_atlas not found in /usr/lib/atlas-base
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/lib/atlas-base
      libraries lapack_atlas not found in /usr/lib/atlas-base
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/atlas-base
      libraries lapack_atlas not found in /usr/lib/atlas-base
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/lib/atlas-base
      libraries lapack_atlas not found in /usr/lib/atlas-base
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    lapack_info:
      libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    lapack_src_info:
      NOT AVAILABLE
    
      NOT AVAILABLE
    
    setup.py:420: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-pqoi2fof'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    Running from scipy source directory.
    /tmp/pip-build-env-i57relwt/overlay/lib/python3.5/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    /tmp/pip-build-env-i57relwt/overlay/lib/python3.5/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    /tmp/pip-build-env-i57relwt/overlay/lib/python3.5/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/build_meta.py", line 267, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/build_meta.py", line 158, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 540, in <module>
        setup_package()
      File "setup.py", line 536, in setup_package
        setup(**metadata)
      File "/tmp/pip-build-env-i57relwt/overlay/lib/python3.5/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 435, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpf029ybs7 Check the logs for full command output.
#
# hardware support
sudo pip3 install --upgrade spidev
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting spidev
  Downloading https://www.piwheels.org/simple/spidev/spidev-3.5-cp35-cp35m-linux_armv7l.whl (39 kB)
Installing collected packages: spidev
  Attempting uninstall: spidev
    Found existing installation: spidev 3.3
ERROR: Cannot uninstall 'spidev'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
sudo pip3 install --upgrade smbus2
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting smbus2
  Using cached https://www.piwheels.org/simple/smbus2/smbus2-0.3.0-py2.py3-none-any.whl (9.1 kB)
Installing collected packages: smbus2
Successfully installed smbus2-0.3.0
sudo pip3 install --upgrade Rpi.bme280
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Rpi.bme280
  Using cached RPi.bme280-0.2.3-py2.py3-none-any.whl (10 kB)
Requirement already satisfied, skipping upgrade: smbus2 in /usr/local/lib/python3.5/dist-packages (from Rpi.bme280) (0.3.0)
Installing collected packages: Rpi.bme280
Successfully installed Rpi.bme280-0.2.3
#
#  ADAfruit for oled and other devices
#  not using them mid-july so leave off
#sudo pip3 install adafruit-blinka
#sudo pip3 install adafruit-circuitpython-bme280
#sudo pip3 install Adafruit-SSD1306
#sudo pip3 install adafruit-circuitpython-ads1x15
#
# getting GTK3 installed
sudo apt install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:6.3.0-4).
libgirepository1.0-dev is already the newest version (1.50.0-1).
pkg-config is already the newest version (0.29-4).
python3-dev is already the newest version (3.5.3-1).
libcairo2-dev is already the newest version (1.14.8-1+rpi1).
gir1.2-gtk-3.0 is already the newest version (3.22.11-1+rpi3).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
sudo pip3 install --upgrade pycairo
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pycairo
  Downloading https://www.piwheels.org/simple/pycairo/pycairo-1.19.1-cp35-cp35m-linux_armv7l.whl (201 kB)
     |████████████████████████████████| 201 kB 161 kB/s 
Installing collected packages: pycairo
Successfully installed pycairo-1.19.1
sudo pip3 install --upgrade PyGObject
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyGObject
  Using cached PyGObject-3.36.1.tar.gz (716 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: pycairo>=1.11.1 in /usr/local/lib/python3.5/dist-packages (from PyGObject) (1.19.1)
Building wheels for collected packages: PyGObject
  Building wheel for PyGObject (PEP 517) ... done
  Created wheel for PyGObject: filename=PyGObject-3.36.1-cp35-cp35m-linux_armv7l.whl size=704347 sha256=27ecc14dde8910bc3ec7eb01b6d8d81ced73fc42032937899841391a02d7867a
  Stored in directory: /root/.cache/pip/wheels/94/9b/5e/01b756cb8189822caa8bf145d2853308d7b6ff2d51fa9424b4
Successfully built PyGObject
Installing collected packages: PyGObject
  Attempting uninstall: PyGObject
    Found existing installation: pygobject 3.22.0
ERROR: Cannot uninstall 'pygobject'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
sudo apt-get -y install glade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
glade is already the newest version (3.20.0-2+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
#
sudo pip3 install thermocouples_reference scipy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting thermocouples_reference
  Using cached thermocouples_reference-0.20.tar.gz (17 kB)
Collecting scipy
  Using cached scipy-1.4.1.tar.gz (24.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp0ho10w7g
         cwd: /tmp/pip-install-dcb7xlm7/scipy
    Complete output (114 lines):
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_lapack_info:
      libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    system_info:
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/lib/atlas-base
      libraries lapack_atlas not found in /usr/lib/atlas-base
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/lib/atlas-base
      libraries lapack_atlas not found in /usr/lib/atlas-base
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/atlas-base
      libraries lapack_atlas not found in /usr/lib/atlas-base
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/lib/atlas-base
      libraries lapack_atlas not found in /usr/lib/atlas-base
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    lapack_info:
      libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    lapack_src_info:
      NOT AVAILABLE
    
      NOT AVAILABLE
    
    setup.py:420: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-kvfjfsle'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    Running from scipy source directory.
    /tmp/pip-build-env-q8n04en8/overlay/lib/python3.5/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    /tmp/pip-build-env-q8n04en8/overlay/lib/python3.5/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    /tmp/pip-build-env-q8n04en8/overlay/lib/python3.5/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/build_meta.py", line 267, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/build_meta.py", line 158, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 540, in <module>
        setup_package()
      File "setup.py", line 536, in setup_package
        setup(**metadata)
      File "/tmp/pip-build-env-q8n04en8/overlay/lib/python3.5/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 435, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp0ho10w7g Check the logs for full command output.
#
#sudo python3 -m pip install -U trio
sudo pip3 install --upgrade pexpect
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pexpect
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.6.0-py2.py3-none-any.whl (39 kB)
Installing collected packages: ptyprocess, pexpect
Successfully installed pexpect-4.8.0 ptyprocess-0.6.0
sudo pip3 install --upgrade trio
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting trio
  Downloading https://www.piwheels.org/simple/trio/trio-0.16.0-py3-none-any.whl (337 kB)
     |████████████████████████████████| 337 kB 164 kB/s 
ERROR: Package 'trio' requires a different Python: 3.5.3 not in '>=3.6'
sudo pip3 install --upgrade pylint
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pylint
  Using cached pylint-2.5.3-py3-none-any.whl (324 kB)
Collecting toml>=0.7.1
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting mccabe<0.7,>=0.6
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting astroid<=2.5,>=2.4.0
  Using cached astroid-2.4.2-py3-none-any.whl (213 kB)
Requirement already satisfied, skipping upgrade: isort<5,>=4.2.5 in /usr/lib/python3/dist-packages (from pylint) (4.2.5)
Requirement already satisfied, skipping upgrade: six~=1.12 in /usr/lib/python3/dist-packages (from astroid<=2.5,>=2.4.0->pylint) (1.12.0)
Collecting typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8"
  Downloading https://www.piwheels.org/simple/typed-ast/typed_ast-1.4.1-cp35-cp35m-linux_armv7l.whl (631 kB)
     |████████████████████████████████| 631 kB 161 kB/s 
Collecting wrapt~=1.11
  Downloading https://www.piwheels.org/simple/wrapt/wrapt-1.12.1-cp35-cp35m-linux_armv7l.whl (66 kB)
     |████████████████████████████████| 66 kB 272 kB/s 
Collecting lazy-object-proxy==1.4.*
  Downloading https://www.piwheels.org/simple/lazy-object-proxy/lazy_object_proxy-1.4.3-cp35-cp35m-linux_armv7l.whl (39 kB)
Installing collected packages: toml, mccabe, typed-ast, wrapt, lazy-object-proxy, astroid, pylint
  Attempting uninstall: typed-ast
    Found existing installation: typed-ast 0.6.3
    Uninstalling typed-ast-0.6.3:
      Successfully uninstalled typed-ast-0.6.3
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.9.0
ERROR: Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
sudo pip3 install --upgrade pynng
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pynng
  Using cached pynng-0.5.0.tar.gz (668 kB)
Collecting cffi
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.14.1-cp35-cp35m-linux_armv7l.whl (316 kB)
Collecting sniffio
  Using cached sniffio-1.1.0-py3-none-any.whl (4.5 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting contextvars>=2.1; python_version < "3.7"
  Downloading https://www.piwheels.org/simple/contextvars/contextvars-2.4-py3-none-any.whl (7.7 kB)
Collecting immutables>=0.9
  Downloading https://www.piwheels.org/simple/immutables/immutables-0.14-cp35-cp35m-linux_armv7l.whl (91 kB)
     |████████████████████████████████| 91 kB 163 kB/s 
Building wheels for collected packages: pynng
  Building wheel for pynng (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3a0slah1/pynng/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3a0slah1/pynng/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-jkcs4s_c
       cwd: /tmp/pip-install-3a0slah1/pynng/
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  Cloning into 'mbedtls'...
  Note: checking out '04a049bda1ceca48060b57bc4bcf5203ce591421'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by performing another checkout.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -b with the checkout command again. Example:
  
    git checkout -b <new-branch-name>
  
  HEAD is now at 04a049bda... Merge remote-tracking branch 'origin/pr/2823' into mbedtls-2.16
  building mbedtls with: ['cmake', '-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true', '-DENABLE_PROGRAMS=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=../prefix', '..']
  error: [Errno 2] No such file or directory: 'cmake'
  ----------------------------------------
  ERROR: Failed building wheel for pynng
  Running setup.py clean for pynng
Failed to build pynng
DEPRECATION: Could not build wheels for pynng which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: pycparser, cffi, immutables, contextvars, sniffio, pynng
    Running setup.py install for pynng ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3a0slah1/pynng/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3a0slah1/pynng/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rk1lyw2d/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.5/pynng
         cwd: /tmp/pip-install-3a0slah1/pynng/
    Complete output (18 lines):
    running install
    running build
    running build_py
    Cloning into 'mbedtls'...
    Note: checking out '04a049bda1ceca48060b57bc4bcf5203ce591421'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b <new-branch-name>
    
    HEAD is now at 04a049bda... Merge remote-tracking branch 'origin/pr/2823' into mbedtls-2.16
    building mbedtls with: ['cmake', '-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true', '-DENABLE_PROGRAMS=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=../prefix', '..']
    error: [Errno 2] No such file or directory: 'cmake'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3a0slah1/pynng/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3a0slah1/pynng/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rk1lyw2d/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.5/pynng Check the logs for full command output.
sudo pip3 install --upgrade pytest
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pytest
  Using cached pytest-6.0.1-py3-none-any.whl (270 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Using cached importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting py>=1.8.2
  Using cached py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting more-itertools>=4.0.0
  Using cached more_itertools-8.4.0-py3-none-any.whl (43 kB)
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied, skipping upgrade: toml in /usr/local/lib/python3.5/dist-packages (from pytest) (0.10.1)
Collecting pathlib2>=2.2.0; python_version < "3.6"
  Downloading pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Collecting attrs>=17.4.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting packaging
  Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting iniconfig
  Using cached iniconfig-1.0.1-py3-none-any.whl (4.2 kB)
Collecting zipp>=0.5
  Downloading zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from pathlib2>=2.2.0; python_version < "3.6"->pytest) (1.12.0)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: zipp, importlib-metadata, py, more-itertools, pluggy, pathlib2, attrs, pyparsing, packaging, iniconfig, pytest
Successfully installed attrs-19.3.0 importlib-metadata-1.7.0 iniconfig-1.0.1 more-itertools-8.4.0 packaging-20.4 pathlib2-2.3.5 pluggy-0.13.1 py-1.9.0 pyparsing-2.4.7 pytest-6.0.1 zipp-1.2.0
#
sudo pip3 install singleton_decorator
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting singleton_decorator
  Using cached https://www.piwheels.org/simple/singleton-decorator/singleton_decorator-1.0.0-py3-none-any.whl (5.1 kB)
Installing collected packages: singleton-decorator
Successfully installed singleton-decorator-1.0.0
#
sudo apt autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

